services:
  iosmb:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - IOSMB_SERVER_IP=${IOSMB_SERVER_IP}
      - IOSMB_SERVER_PORT=${IOSMB_SERVER_PORT}
      - IOSMB_SERVER_PASSWORD=${IOSMB_SERVER_PASSWORD}
      - IOSMB_SERVER_SSL=${IOSMB_SERVER_SSL}
      - IOSMB_WEB_USERNAME=${IOSMB_WEB_USERNAME}
      - IOSMB_WEB_PASSWORD_HASH=${IOSMB_WEB_PASSWORD_HASH}
